### ISSUE TITLE
CaseRoles sheet needs to be added to the data/ccd-template.xlsx

### ISSUE THREAD

**Issue by mounikahmcts** [hmcts/ccd-definition-processor#17]
### What would you like to change?
New sheet to be added (CaseRoles) - Divorce App would like to use it.
Refer CCD_TestDefinition_V41_RDM-4362.xlsx in the ccd-definition-store-api

### If this entry is related to a bug, please provide the steps to reproduce it

https://github.com/hmcts/ccd-definition-store-api/blob/master/application/src/test/resources/CCD_TestDefinition_V41_RDM-4362.xlsx

**Comment by geek-soft** [comment]
Addressed in https://github.com/hmcts/ccd-definition-processor/pull/22
