### ISSUE TITLE
New AuthorisationComplexType tab on ccd needs to be added 

### ISSUE THREAD

**Issue by qzhou-hmcts** [hmcts/ccd-definition-processor#19]
### What would you like to change?
Add new _AuthorisationComplexType_ tab on excel definition

### How do you think that would improve the project?
keep up to date with the latest ccd configuration

### If this entry is related to a bug, please provide the steps to reproduce it
No

**Comment by timja** [comment]
Closed in https://github.com/hmcts/ccd-definition-processor/pull/20
